# build stage
FROM node:20-bullseye-slim as BUILD

WORKDIR /usr/src/api
COPY package*.json /usr/src/api

RUN npm ci

# final stage
FROM node:20-bullseye-slim

USER node
WORKDIR /usr/src/api

COPY --chown=node:node --from=build /usr/src/api/node_modules /usr/src/api/node_modules
COPY --chown=node:node . /usr/src/api

CMD ["npm", "run", "start:debug"]