# build stage
FROM node:20-bullseye-slim as BUILD

RUN apt-get update && apt-get install -y --no-install-recommends dumb-init
WORKDIR /usr/src/web
COPY package.json /usr/src/web/

RUN npm install
CMD "npm" "start"

# final stage
FROM node:20-bullseye-slim

COPY --from=build /usr/bin/dumb-init /usr/bin/dumb-init
USER node
WORKDIR /usr/src/web

COPY --chown=node:node --from=build /usr/src/web/node_modules /usr/src/web/node_modules
COPY --chown=node:node . /usr/src/web

